// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQQV6S3-RcOm17iVwj6I7qOl0J4Vdm5U',
    appId: '1:583764575382:web:3adb3467defedf5b332eb7',
    messagingSenderId: '583764575382',
    projectId: 'flutter-multimedia',
    authDomain: 'flutter-multimedia.firebaseapp.com',
    databaseURL: 'https://flutter-multimedia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-multimedia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4lw5ydOZOvJv_ONPhqJ9CO0ET70SqpJw',
    appId: '1:583764575382:android:b4ef2d277294cac5332eb7',
    messagingSenderId: '583764575382',
    projectId: 'flutter-multimedia',
    databaseURL: 'https://flutter-multimedia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-multimedia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4z-sEfI4y5lNHrjDmhpW2Am6W57GH-3Q',
    appId: '1:583764575382:ios:33d5718cbab10dbe332eb7',
    messagingSenderId: '583764575382',
    projectId: 'flutter-multimedia',
    databaseURL: 'https://flutter-multimedia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-multimedia.firebasestorage.app',
    iosBundleId: 'com.example.productesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSQQV6S3-RcOm17iVwj6I7qOl0J4Vdm5U',
    appId: '1:583764575382:web:f757b91802ae5b1d332eb7',
    messagingSenderId: '583764575382',
    projectId: 'flutter-multimedia',
    authDomain: 'flutter-multimedia.firebaseapp.com',
    databaseURL: 'https://flutter-multimedia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-multimedia.firebasestorage.app',
  );
}
